version: '3'

tasks:
  create-repo:
    vars:
      REPOSITORIES: |
        trip
        car
        hotel
        flight

    cmds:
      - |
        ARR=(`echo "{{.REPOSITORIES}}" | tr '\n' ' '`)
        for REPO in ${ARR[@]}
        do
          aws ecr create-repository --repository-name ${REPO} {{.CLI_ARGS}}
        done
