[app]
ns="DevOpsDemo"
stage="Dev"

[aws]
account="" # e.g. 123456789012
region="ap-northeast-2"

[vpc]
id="" # e.g. vpc-xxx

[msk]
seeds="" # e.g. xxx:9094,yyy:9094
securityGroupId="" # e.g. sg-xxx

[service]
[service.common]
port=8090
tag="a4b77e5b7d"

[service.trip]
name="trip"
repositoryName="trip"

[service.car]
name="car"
repositoryName="car"

[service.hotel]
name="hotel"
repositoryName="hotel"

[service.flight]
name="flight"
repositoryName="flight"

[ddb]
tableName="trip"