[app]
ns="EksDemo"
stage="Dev"

[aws]
account=""
region="ap-northeast-2"

[vpc]
id=""

[service]
trip.name="trip"
trip.repositoryName="trip"
car.name="car"
car.repositoryName="car"
hotel.name="hotel"
hotel.repositoryName="hotel"
flight.name="flight"
flight.repositoryName="flight"

[ddb]
tableName="trip"

[securityGroups]
msk=""