[app]
ns="DevOpsAcademy"
stage="Dev"

[aws]
account=""
region="ap-northeast-2"

[vpc]
id=""

[service]
[service.trip]
name="trip"
port=8090
repositoryName="trip"
[service.car]
name="car"
port=8090
repositoryName="car"
[service.hotel]
name="hotel"
port=8090
repositoryName="hotel"
[service.flight]
name="flight"
port=8090
repositoryName="flight"

[ddb]
tableName="trip"

[securityGroups]
msk=""